services:
  - type: web
    name: comment-unlist-app
    env: python
    buildCommand: "pip install -r requirements.txt && python -m nltk.downloader punkt stopwords"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PORT
        value: 10000